// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhjvxvavhjavlhnkloce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoanZ4dmF2aGphdmxobmtsb2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzQ0NjksImV4cCI6MjA2MDM1MDQ2OX0.Ai5HSeEORoUzqAK4VfrwILymmPKBQBZJBVqSA-OCsO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);